### ISSUE TITLE
Update from babel to babel-cli

### ISSUE THREAD

**Issue by kexic** [developer239/ReactReduxApolloGraphQLHotBoilerplate#3]
On fresh npm init:
"npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli."

**Comment by developer239** [comment]
I will look into it this weekend. :)

**Comment by developer239** [comment]
@kexic I just pushed major updates. Please take a look at the new code. I am sure you are gonna like it. :)
